// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/panjf2000/ants/v2/examples/ent/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
